Updates from Kristine's science writer for simpler language
Sage-Bionetworks/synapseDocs pull request #525
Opened 2019-03-07 21:10 UTC by meredithslota

2019-03-07 21:22 UTC, kdaily requested changes

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +`Projects` in Synapse serve as workspaces where researchers collaborate.  Researchers using Synapse can work in private or collaborate in groups. Some users share their research across large consorti
```suggestion
`Projects` in Synapse serve as workspaces where researchers collaborate. Researchers using Synapse can work in private or collaborate in groups. Some users share their research across large consortia. Projects support the following:
```

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +* **Store Data, Code, and Results**: You can upload your data, code, and results to Synapse, or store a reference to their location in your local computer system. Everything can be stored as Files, h
```suggestion
* **Store Data, Code, and Results**: You can upload your data, code, and results to Synapse, or store a reference to their location in your local computer system or on the web. Everything can be stored as Files, hosted by Synapse, in your own external cloud storage, or using [Docker Containers](http://docs.synapse.org/articles/docker.html). 
```

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +* **Control Access or Release Your Work Publicly**: You have complete control over how users and groups can interact with your work. Work privately or collaborate openly, and everything in between.
```suggestion
* **Control Access or Release Your Work Publicly**: You have complete control over how users and groups can interact with your work. Work privately, openly, or somewhere in between.
```

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +* **Describe and Version**: Describe each of the elements in your workflow, and then practice version control when you see fit. This allows you to explicitly record which version of the code you ran
```suggestion
* **Describe and Version**: Describe each element in your workflow and practice version control when you see fit. This allows you to explicitly record which version of the code you ran on which version of the data.
```

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +* **Create Links and See Usage**: You can make a link to store data from elsewhere on Synapse
```suggestion
```

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +* **Create Links and See Usage**: You can make a link to store data from elsewhere on Synapse
added above in the Files that you can link

2019-03-07 21:22 UTC, kdaily commented on articles/making_a_project.md
> +and use it in your project. Other projects using your data are displayed automatically.
```suggestion
```

we don't do this?

2019-07-01 22:34 UTC, kelshmo commented
@kdaily I can't merge despite approving your commits for some reason...

2019-07-01 22:54 UTC, kdaily commented
@kelshmo try again, updated your permissions.

2019-07-01 22:59 UTC, kelshmo approved these changes

2019-10-07 21:44 UTC, merged