Shorten challenge admin docs
Sage-Bionetworks/synapseDocs pull request #528
Opened 2019-03-08 18:30 UTC by thomasyu888

2019-03-08 18:30 UTC, thomasyu888 commented
Also, its not completed. Just opened PR to remind myself of this task

2019-03-15 23:34 UTC, kelshmo reviewed
In-progress review - I want to pull into the dev build to look at format

2019-03-15 23:34 UTC, kelshmo commented on articles/challenge_administration.md
> +**For all DREAM challenges, please contact the Synapse Access and Compliance Team (act@sagebase.org) for step A4!**
what is step A4 - can we explicitly state it here?

2019-03-17 03:23 UTC, tschaffter requested changes
Review (part 1/2)

2019-03-25 20:53 UTC, tschaffter requested changes

2019-03-27 18:08 UTC, kelshmo approved these changes

2019-03-27 19:35 UTC, merged