Add in some information about the leaderboard renderers
Sage-Bionetworks/synapseDocs pull request #638
Opened 2019-10-29 07:25 UTC by thomasyu888

#620

2019-10-31 06:02 UTC, thomasyu888 commented on articles/evaluation_queues.md
> +* markdown link: Support link in markdown format `[my link](url.com)`
```suggestion
* markdown link: Support Synapse wiki markdown format`
```

2019-11-04 22:47 UTC, kdaily requested changes
date/epochdate should be defined separately. See PR https://github.com/thomasyu888/synapseDocs/pull/2 for other changes!

2019-11-04 22:50 UTC, thomasyu888 commented
The issue of date/epochdate is filed in a jira. They are duplicated

2019-11-04 23:00 UTC, kdaily commented
https://sagebionetworks.jira.com/browse/SWC-4972 for reference. I would suggest we only document one (`date`) and say the other one is deprecated. Then file a separate issue to remove `epochdate` from the docs page when it's removed.

2019-11-06 00:42 UTC, jay-hodgson commented on articles/evaluation_queues.md
> +* date/epochdate: Renders epochtime in milliseconds to local time
Note that in the web client, the user can select to show dates in UTC (in user settings) rather than local time.

2019-12-09 22:33 UTC, kdaily approved these changes

2019-12-09 22:33 UTC, merged