Add doc about submission widget
Sage-Bionetworks/synapseDocs pull request #644
Opened 2019-10-31 06:00 UTC by thomasyu888

2019-11-14 18:39 UTC, thomasyu888 commented on articles/evaluation_queues.md
> +**Alpha Mode Feature:** Present a custom HTML form to the user to fill out during submission.  This form is built using [react JSON schema](https://react-jsonschema-form.readthedocs.io/en/latest/). B
```suggestion
```

2019-11-14 18:39 UTC, thomasyu888 commented on articles/evaluation_queues.md
> +<img style="width: 80%;" src="/assets/images/submission_react_widget.png">
```suggestion```

2020-04-13 20:42 UTC, kelshmo commented
@thomasyu888 What further actions should be taken with this PR? Thanks!

2020-04-13 20:53 UTC, thomasyu888 commented
Thanks @kelshmo, this is all.

2020-04-13 22:09 UTC, kelshmo requested changes
I'm not so familiar with Evaluation queues, so let me know if these proposed edits change the meaning. Thanks Tom!

2020-04-13 22:09 UTC, kelshmo commented on _articles/evaluation_queues.md
> +Aside from directing people to submit to an evaluation queue by navigating to an Synapse Entity, you can also add a `Submit To Evaluation` widget on a wiki page. Here you will get an option of allowi
```suggestion
You may embed a `Submit To Evaluation` widget on a Wiki page to improve visibility of your Evaluation queue. The widget allows participants to submit to multiple Evaluation queues within a Project or a single Evaluation queue. 

Currently, this Wiki widget is required to submit Synapse Projects to an Evaluation queue. Synapse Docker repositories can not be submitted through this widget.
```

2020-04-13 22:09 UTC, kelshmo commented on _articles/evaluation_queues.md
> +Aside from directing people to submit to an evaluation queue by navigating to an Synapse Entity, you can also add a `Submit To Evaluation` widget on a wiki page. Here you will get an option of allowi
Mostly style updates.

Do my edits preserve the meaning of your intended edits?

2020-04-15 08:22 UTC, thomasyu888 commented on _articles/evaluation_queues.md
> +### Adding Submit to Evaluation Widget
```suggestion
### Submit to an Evaluation Queue from a Wiki Page
```

2020-04-15 08:28 UTC, thomasyu888 commented on _articles/evaluation_queues.md
> +<img style="width: 80%;" src="/assets/images/submit_to_evaluation_widget.png">
Perhaps,  I _think_ these are some of the scenarios where a evaluation queue would be unavailable:

1. User does not have permission to view the evaluation queues
2. The specified challenge doesn't have evaluation queues. 
3. There are no "open" evaluation queues (you can set quotas on time durations on evaluation queues and have them automatically 'close' after some time)

Both of these messages would occur after the creation of his widget though.

2020-04-16 03:45 UTC, kelshmo commented on _articles/evaluation_queues.md
> +<img style="width: 80%;" src="/assets/images/submit_to_evaluation_widget.png">
In the image you uploaded of the widget - there is a field to enter an "Evaluation Queue unavailable message" and I'm not sure that it is clear that the creator can, or why they would, customize this message. 

The points you listed here might be relevant to be incorporate into "Configuring Leaderboard Widget"

2020-04-16 03:46 UTC, kelshmo reviewed
Should we incorporate those points about EQ unavailability into the "Configuring Leaderboard Widget" section?

2020-04-21 21:11 UTC, kelshmo approved these changes

2020-04-21 21:11 UTC, kelshmo commented on _articles/evaluation_queues.md
> +<img style="width: 80%;" src="/assets/images/submit_to_evaluation_widget.png">
See #755 and #754

2020-04-21 21:11 UTC, merged