Issue 583
Sage-Bionetworks/synapseDocs pull request #647
Opened 2019-11-08 03:17 UTC by brucehoff

2019-11-08 03:17 UTC, brucehoff commented
https://github.com/Sage-Bionetworks/synapseDocs/issues/583

2019-11-08 19:42 UTC, kdaily requested changes
Minor changes, but looks good overall!

Please consider adding in a short section that says what statistics they will get by doing this, instead of relying on the user going to the page to see an example.

2019-11-08 19:42 UTC, kdaily commented on articles/challenge_administration.md
> +One of the features of Synapse for DREAM Challenges is the live compilation of submission statistics for all evaluation queues.  You can see the stat's for various challenges [here](https://www.synap
```suggestion
One of the features of Synapse for DREAM Challenges is the live compilation of submission statistics for all evaluation queues.  You can see the statistics for various challenges [here](https://www.synapse.org/#!Synapse:syn2504723/wiki/65150).  In order to activate statistics for your evaluation queues:
```

2019-11-08 19:42 UTC, kdaily commented on articles/challenge_administration.md
> +<br/>
```suggestion
```

2019-11-08 19:42 UTC, kdaily commented on articles/challenge_administration.md
> +
```suggestion
```

2019-11-11 17:46 UTC, brucehoff commented
I made the requested changes.  Kindly review and merge.

2019-11-12 06:12 UTC, thomasyu888 reviewed
I really like this, but the challenge statistics page is not a public page.  I wonder if we need to also add a short description of how someone would gain access to this page.

2019-11-12 17:39 UTC, kdaily commented on articles/challenge_administration.md
> +One of the features of Synapse for DREAM Challenges is the live compilation of submission statistics for all evaluation queues, including total submission count, count per individual/team, count per
Per @thomasyu888:
```suggestion
One of the features of Synapse for DREAM Challenges is the live compilation of submission statistics for all evaluation queues, including total submission count, count per individual/team, count per submission state (scored, invalid) and count per week.  You can see the statistics for various challenges [here](https://www.synapse.org/#!Synapse:syn2504723/wiki/65150).  In order to activate statistics for your evaluation queues, you must be an administrator of the challenge Project. Each queue needs to be configured to generate the statistics. To do this:
```

2019-11-12 17:42 UTC, brucehoff commented
@thomasyu888 I made the page visible to all logged-in users.

2019-11-15 18:54 UTC, kdaily commented on articles/challenge_administration.md
> +One of the features of Synapse for DREAM Challenges is the live compilation of submission statistics for all evaluation queues, including total submission count, count per individual/team, count per
@brucehoff can you review and merge this suggested change? I cannot do so. Thank you!

2019-11-15 19:39 UTC, kdaily approved these changes
LG!

2019-11-15 19:39 UTC, merged