Note Anonymous Wiki Viewing
Sage-Bionetworks/synapseDocs pull request #655
Opened 2019-11-12 00:20 UTC by kelshmo

Fixes #455. 

Style fixes: 
- Bold buttons 
- removed redundant ``

2019-11-12 06:02 UTC, thomasyu888 approved these changes

2019-11-12 17:47 UTC, kdaily requested changes
minor change! thanks @kelshmo looks good!

2019-11-12 17:47 UTC, kdaily commented on articles/wikis.md
> +Wikis inherit their [sharing settings](https://docs.synapse.org/articles/sharing_settings.html) from the Project, Folder, or File it is associated with, and cannot have separate sharing settings. Any
```suggestion
A Wiki inherits it's [sharing settings](https://docs.synapse.org/articles/sharing_settings.html) from the Project, Folder, or File it is associated with, and cannot have separate sharing settings. Anyone with 'view' permissions or greater can see the content of the Wiki page. When a Project, Folder or File is shared with the public, the associated Wiki is visible to viewers who are not logged in to Synapse.
```

2019-11-15 19:41 UTC, kdaily approved these changes

2019-11-15 19:41 UTC, merged