Add NTAP to supporting funders list (they are on the synapse footer already).
Sage-Bionetworks/synapseDocs pull request #799
Opened 2020-07-16 21:49 UTC by allaway

This pull request has been automatically generated by prose.io.

2020-07-17 17:58 UTC, kelshmo commented
Yay, prose!

2020-07-17 18:01 UTC, kelshmo requested changes

2020-07-17 18:01 UTC, kelshmo commented on _articles/faq.md
> +published: true
@allaway did prose add this to the yaml? I don't think this will be interpreted in the build.

2020-07-17 20:32 UTC, allaway commented
Hey Kelsey - yes, it did. I PRed anyway because I thought that the branches
were set up to build before merging, to see if this would work, but i guess
the branches dont' automatically build?

Anyways, I'll check to see if there is a prose-side configuration I can
change to fix this.

To be honest, the purpose of this PR was more to test out prose, I just
happened to find this change as something I could make while testing :)



On Fri, Jul 17, 2020 at 11:01 AM Kelsey Montgomery <notifications@github.com>
wrote:

> *@kelshmo* requested changes on this pull request.
> ------------------------------
>
> In _articles/faq.md
> <https://github.com/Sage-Bionetworks/synapseDocs/pull/799#discussion_r456593918>
> :
>
> >  layout: article
>  excerpt: What is Synapse?
>  order: 4
> +published: true
>
> @allaway <https://github.com/allaway> did prose add this to the yaml? I
> don't think this will be interpreted in the build.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sage-Bionetworks/synapseDocs/pull/799#pullrequestreview-450856201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE3WNSG66ANE5Q2USBE5Q53R4CGXZANCNFSM4O475UQQ>
> .
>

2020-07-27 20:31 UTC, kelshmo commented
The GH Actions build is currently not set-up however, I tested this locally with Jekyll and it is building fine. 

The `published:true` tag is being ignored. I will probably just remove it to not have it as an artifact in the code that is currently not functional - do you want to push these changes to the live site?

2020-07-28 13:17 UTC, allaway commented
Yep! I removed the `published: true tag`, feel free to merge if you are happy with it! 

I took a look around and found [this issue](https://github.com/prose/prose/issues/1097), it doesn't look like we're the only one experiencing this. 

I'll take a look at some other editors to see how easy they are and whether they do anything unexpected like this.

2020-07-28 19:38 UTC, kelshmo approved these changes

2020-07-28 19:38 UTC, merged

2022-09-25 16:39 UTC, hmua commented
> Yep! I removed the `published: true tag`, feel free to merge if you are happy with it!
> 
> I took a look around and found [this issue](https://github.com/prose/prose/issues/1097), it doesn't look like we're the only one experiencing this.
> 
> I'll take a look at some other editors to see how easy they are to use and whether they do anything unexpected like this. Prose is nice because it obfuscates a lot of git jargon away...

Could you please help to point out how to do this?